import { env } from '../config/env.js';
import * as membership from '../services/workspace/membershipService.js';
import { getWorkspaceStats } from '../services/workspace/statsService.js';
import { signAccessToken, signRefreshToken, setRefreshCookie } from '../services/auth/tokenService.js';
import { sendCreated, sendSuccess } from '../utils/ApiResponse.js';
import asyncHandler from '../utils/asyncHandler.js';

const clientUrl = () => env.CLIENT_URL?.replace(/\/$/, '') ?? '';

/** The caller's own workspace context — used by the UI to show the right nav. */
export const context = asyncHandler(async (req, res) =>
  sendSuccess(res, {
    message: 'OK',
    data: { workspaceId: req.workspaceId, role: req.wsRole },
  }),
);

/** Workspace dashboard stats — owner/admin only (enforced by the route). */
export const stats = asyncHandler(async (req, res) => {
  const data = await getWorkspaceStats(req.workspaceId);
  return sendSuccess(res, { message: 'OK', data });
});

/** Team list — owner/admin only (enforced by the route). */
export const members = asyncHandler(async (req, res) => {
  const list = await membership.listMembers(req.workspaceId);
  return sendSuccess(res, {
    message: 'OK',
    data: {
      members: list.map((m) => ({
        id: m._id,
        userId: m.userId?._id ?? m.userId,
        name: m.userId?.name ?? '',
        email: m.userId?.email ?? '',
        role: m.role,
        status: m.status,
      })),
    },
  });
});

/** Create an invite link for the caller's workspace. */
export const invite = asyncHandler(async (req, res) => {
  const { token, role } = await membership.createInvite({
    workspaceId: req.workspaceId,
    email: req.body.email,
    role: req.body.role,
    invitedBy: req.user._id,
  });

  return sendCreated(res, {
    message: 'Invitation created.',
    data: { joinUrl: `${clientUrl()}/join/${token}`, role },
  });
});

export const removeMember = asyncHandler(async (req, res) => {
  await membership.removeMember({ workspaceId: req.workspaceId, memberUserId: req.params.userId });
  return sendSuccess(res, { message: 'Member removed.', data: {} });
});

export const updateMember = asyncHandler(async (req, res) => {
  await membership.updateMemberRole({
    workspaceId: req.workspaceId,
    memberUserId: req.params.userId,
    role: req.body.role,
  });
  return sendSuccess(res, { message: 'Role updated.', data: {} });
});

/** Public: what a join token points at (name a password field, show the role). */
export const joinInfo = asyncHandler(async (req, res) => {
  const invite = await membership.getUsableInvite(req.params.token);
  if (!invite) {
    return sendSuccess(res, { message: 'OK', data: { valid: false } });
  }
  return sendSuccess(res, {
    message: 'OK',
    data: { valid: true, role: invite.role, email: invite.email },
  });
});

/** Public: accept the invite, create/attach the user, and log them straight in. */
export const acceptJoin = asyncHandler(async (req, res) => {
  const { user } = await membership.acceptInvite({
    rawToken: req.params.token,
    name: req.body.name,
    password: req.body.password,
  });

  return issueSessionFor(res, user);
});

/**
 * Public: owner activation with the email + code generated by the hub. Rate
 * limited by the route so the short code can't be brute-forced.
 */
export const activate = asyncHandler(async (req, res) => {
  const { user } = await membership.acceptByCode({
    email: req.body.email,
    code: req.body.code,
    name: req.body.name,
    password: req.body.password,
  });

  return issueSessionFor(res, user);
});

/** Signs the user in (access token + refresh cookie) and returns the session. */
function issueSessionFor(res, user) {
  setRefreshCookie(res, signRefreshToken(user));
  return sendSuccess(res, {
    message: 'Welcome to the workspace.',
    data: {
      accessToken: signAccessToken(user),
      user: { id: user._id, name: user.name, email: user.email },
    },
  });
}

export default {
  context,
  stats,
  members,
  invite,
  removeMember,
  updateMember,
  joinInfo,
  acceptJoin,
  activate,
};
